backend:
  name: github
  repo: mrMetalWood/brauselier # Path to your Github repository
  branch: develop # Branch to update

media_folder: "src/pages/posts/static"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Article Image", name: "articleImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
